services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:${VERSION}
    network_mode: "host"
    volumes:
      - ../certs:/usr/share/filebeat/certs:z
      - data:/usr/share/filebeat/data
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:z
      - /var/log/httpd:/usr/share/filebeat/logs_mount:z
    user: root

volumes:
  data:
    driver: local
